PROJECT_DATA: data
PROJECT_LOG: log

DATA:
  TEST_SIZE: 0.20
  NUM_WORKERS: 4

PATH_CPSMI2025: CPSMI2025/CPSMI2025
PATH_HERLEV: Herlev Dataset
PATH_MENDELEYLBC: MendeleyLBC
PATH_SIPAKMED: SIPaKMeD
PATH_HICERVIX: HiCervix

PATH_PRETRAINED: pretrained
PATH_FINETUNED: finetuned

PRETRAINING:
  BATCH_SIZE: 32
  FROZEN_EPOCHS:   2 # 10
  UNFROZEN_EPOCHS: 1 # 40

  FROZEN_LR:   0.0001 # 1e-4
  UNFROZEN_LR: 0.001  # 1e-3
  TEMPERATURE: 0.5
  VALIDATION_SIZE: 0.10
  SAVE_EVERY: 3

  LORA:
    R: 8
    ALPHA: 16
    DROPOUT: 0.0

DOWNSTREAM:
  BATCH_SIZE: 16
  ACCUMULATION_STEPS: 2
  FROZEN_EPOCHS:   2 # 10
  UNFROZEN_EPOCHS: 1 # 40

  FROZEN_LR:   0.0001 # 1e-4
  UNFROZEN_LR: 0.001  # 1e-3
  SAVE_EVERY: 3
