PROJECT_DATA: data
PROJECT_LOG: log

DATA:
  TEST_SIZE: 0.20
  NUM_WORKERS: 4

PATH_BTM: BTM
PATH_CPSMI2025: CPSMI2025/CPSMI2025
PATH_HERLEV: Herlev Dataset
PATH_MENDELEYLBC: MendeleyLBC
PATH_SIPAKMED: SIPaKMeD
PATH_HICERVIX: HiCervix
PATH_PAPICITO: Papicito

PATH_PRETRAINED: pretrained
PATH_FINETUNED: finetuned

PRETRAINING:
  RESUME: false
  BATCH_SIZE: 32
  FROZEN_EPOCHS:   5
  UNFROZEN_EPOCHS: 45

  FROZEN_LR:   0.001  # 1e-3
  UNFROZEN_LR: 0.0001 # 1e-4
  TEMPERATURE: 0.5
  VALIDATION_SIZE: 0.10
  SAVE_EVERY: 3

  LORA:
    R: 8
    ALPHA: 16
    DROPOUT: 0.0

DOWNSTREAM:
  FROM_PRETRAINED: local
  # FROM_PRETRAINED: base
  
  BATCH_SIZE: 32
  ACCUMULATION_STEPS: 1
  FROZEN_EPOCHS:   10
  UNFROZEN_EPOCHS: 40

  FROZEN_LR:   0.001  # 1e-3
  UNFROZEN_LR: 0.0001 # 1e-4
  SAVE_EVERY: 3
